// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import ()

type Card struct {
	ID     int64
	Time   string
	Date   string
	Title  string
	Client string
	User   string
}
